language: node_js
node_js:
  - "5"
  - "5.6.0"
  - "4.4.3"
  - "4"

before_script:
  - sudo apt-get install -y jq
  - source .env-sample
  - npm run mkdir:data
  - npm run data:places
  - npm run data:trips
